config/routes.rb
ServerScaffold::Application.routes.draw do
  get "sessions/new"

  resources :histories do
    collection do
      get :destroy_all
    end
  end

  resources :devices
  
  resources :sessions, only: [:new, :create, :destroy]
  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  
  resources :locations do
    collection do
      get :newlocation
    end
    member do
      get :indoor
    end
    resources :lights do
      collection do
        get :newlight
      end
      member do
        get :dragdrop
      end
    end
  end

  resources :users

  root :to => "pages#home"

  match '/about',   :to => 'pages#about'

  match '/signup',  :to => 'users#new'
  
end

#== Route Map
# Generated on 30 Apr 2012 18:08
#
#    destroy_all_histories GET    /histories/destroy_all(.:format)                      {:action=>"destroy_all", :controller=>"histories"}
#                histories GET    /histories(.:format)                                  {:action=>"index", :controller=>"histories"}
#                          POST   /histories(.:format)                                  {:action=>"create", :controller=>"histories"}
#              new_history GET    /histories/new(.:format)                              {:action=>"new", :controller=>"histories"}
#             edit_history GET    /histories/:id/edit(.:format)                         {:action=>"edit", :controller=>"histories"}
#                  history GET    /histories/:id(.:format)                              {:action=>"show", :controller=>"histories"}
#                          PUT    /histories/:id(.:format)                              {:action=>"update", :controller=>"histories"}
#                          DELETE /histories/:id(.:format)                              {:action=>"destroy", :controller=>"histories"}
#                  devices GET    /devices(.:format)                                    {:action=>"index", :controller=>"devices"}
#                          POST   /devices(.:format)                                    {:action=>"create", :controller=>"devices"}
#               new_device GET    /devices/new(.:format)                                {:action=>"new", :controller=>"devices"}
#              edit_device GET    /devices/:id/edit(.:format)                           {:action=>"edit", :controller=>"devices"}
#                   device GET    /devices/:id(.:format)                                {:action=>"show", :controller=>"devices"}
#                          PUT    /devices/:id(.:format)                                {:action=>"update", :controller=>"devices"}
#                          DELETE /devices/:id(.:format)                                {:action=>"destroy", :controller=>"devices"}
#                 sessions POST   /sessions(.:format)                                   {:action=>"create", :controller=>"sessions"}
#              new_session GET    /sessions/new(.:format)                               {:action=>"new", :controller=>"sessions"}
#                  session DELETE /sessions/:id(.:format)                               {:action=>"destroy", :controller=>"sessions"}
#                   signup        /signup(.:format)                                     {:controller=>"users", :action=>"new"}
#                   signin        /signin(.:format)                                     {:controller=>"sessions", :action=>"new"}
#                  signout DELETE /signout(.:format)                                    {:controller=>"sessions", :action=>"destroy"}
#    newlocation_locations GET    /locations/newlocation(.:format)                      {:action=>"newlocation", :controller=>"locations"}
#          indoor_location GET    /locations/:id/indoor(.:format)                       {:action=>"indoor", :controller=>"locations"}
# newlight_location_lights GET    /locations/:location_id/lights/newlight(.:format)     {:action=>"newlight", :controller=>"lights"}
#  dragdrop_location_light GET    /locations/:location_id/lights/:id/dragdrop(.:format) {:action=>"dragdrop", :controller=>"lights"}
#          location_lights GET    /locations/:location_id/lights(.:format)              {:action=>"index", :controller=>"lights"}
#                          POST   /locations/:location_id/lights(.:format)              {:action=>"create", :controller=>"lights"}
#       new_location_light GET    /locations/:location_id/lights/new(.:format)          {:action=>"new", :controller=>"lights"}
#      edit_location_light GET    /locations/:location_id/lights/:id/edit(.:format)     {:action=>"edit", :controller=>"lights"}
#           location_light GET    /locations/:location_id/lights/:id(.:format)          {:action=>"show", :controller=>"lights"}
#                          PUT    /locations/:location_id/lights/:id(.:format)          {:action=>"update", :controller=>"lights"}
#                          DELETE /locations/:location_id/lights/:id(.:format)          {:action=>"destroy", :controller=>"lights"}
#                locations GET    /locations(.:format)                                  {:action=>"index", :controller=>"locations"}
#                          POST   /locations(.:format)                                  {:action=>"create", :controller=>"locations"}
#             new_location GET    /locations/new(.:format)                              {:action=>"new", :controller=>"locations"}
#            edit_location GET    /locations/:id/edit(.:format)                         {:action=>"edit", :controller=>"locations"}
#                 location GET    /locations/:id(.:format)                              {:action=>"show", :controller=>"locations"}
#                          PUT    /locations/:id(.:format)                              {:action=>"update", :controller=>"locations"}
#                          DELETE /locations/:id(.:format)                              {:action=>"destroy", :controller=>"locations"}
#                    users GET    /users(.:format)                                      {:action=>"index", :controller=>"users"}
#                          POST   /users(.:format)                                      {:action=>"create", :controller=>"users"}
#                 new_user GET    /users/new(.:format)                                  {:action=>"new", :controller=>"users"}
#                edit_user GET    /users/:id/edit(.:format)                             {:action=>"edit", :controller=>"users"}
#                     user GET    /users/:id(.:format)                                  {:action=>"show", :controller=>"users"}
#                          PUT    /users/:id(.:format)                                  {:action=>"update", :controller=>"users"}
#                          DELETE /users/:id(.:format)                                  {:action=>"destroy", :controller=>"users"}
#                     root        /(.:format)                                           {:controller=>"pages", :action=>"home"}
#                    about        /about(.:format)                                      {:controller=>"pages", :action=>"about"}
#                                 /signup(.:format)                                     {:controller=>"users", :action=>"new"}

app/models/light.rb
# == Schema Information
#
# Table name: lights
#
#  id          :integer         not null, primary key
#  x_position  :integer
#  y_position  :integer
#  z_position  :integer
#  location_id :integer
#  light_id    :integer
#  name        :string(255)
#  content     :binary
#  created_at  :datetime
#  updated_at  :datetime
#

class Light < ActiveRecord::Base
  attr_accessible :x_position, :y_position, :z_position, :location_id
  attr_accessible :light_id, :name, :content

  has_many :devices
  has_many :history

  belongs_to :location

  validates :x_position, :presence => true

  validates :y_position, :presence => true

  validates :z_position, :presence => true

  validates :location_id, :presence => true

  validates :light_id, :presence => true

  validates :name, :presence => true,
                   :length   => { :maximum => 50 }

end

app/controllers/lights_controller.rb
class LightsController < ApplicationController

#  helper_method :sort_column, :sort_direction

  # GET /lights
  # GET /lights.xml
  def index
    # @lights = Light.all
    @title = "Lights"
    @location = Location.find(params[:location_id])
    #@lights = @location.lights.all
    @lights = @location.lights.order(sort_column + " " + sort_direction)

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @lights }
      format.json  { render :json => @lights }
    end
  end

  # GET /lights/1
  # GET /lights/1.xml
  def show
    @location = Location.find(params[:location_id])
    @light = @location.lights.find(params[:id])
    # @light = Light.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @light }
      format.json  { render :json => @lights }
    end
  end
  
  # GET /lights/1/dragdrop
  def dragdrop
    @location = Location.find(params[:location_id])
    @light = @location.lights.find(params[:id])
    
    respond_to do |format|
      format.html # dragdrop.html.erb
      format.xml  { render :xml => @light }
      format.json  { render :json => @lights }
    end  
  end

  # GET /lights/new
  # GET /lights/new.xml
  def new
    # @light = Light.new
    @location = Location.find(params[:location_id])
    @light = @location.lights.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @light }
      format.json  { render :json => @lights }
    end
  end
  
  # GET /lights/newlight
  # GET /lights/newlight.xml
  def newlight
    @location = Location.find(params[:location_id])
    @light = @location.lights.new

    respond_to do |format|
      format.html # newlight.html.erb
      format.xml  { render :xml => @light }
    end
  end

  # GET /lights/1/edit
  def edit
    # @light = Light.find(params[:id])
    @location = Location.find(params[:location_id])
    @light = @location.lights.find(params[:id])    
  end

  # POST /lights
  # POST /lights.xml
  def create
    # @light = Light.new(params[:light])
    @location = Location.find(params[:location_id])
    @light = @location.lights.new(params[:light])
    
    respond_to do |format|
      if @light.save
        format.html { redirect_to([@location, @light], :notice => 'Light was successfully created.') }
        format.xml  { render :xml => @light, :status => :created, :location => @light }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @light.errors, :status => :unprocessable_entity }
        format.json  { render :json => @lights }
      end
    end
  end

  # PUT /lights/1
  # PUT /lights/1.xml
  def update
    # @light = Light.find(params[:id])
    @location = Location.find(params[:location_id])
    @light = @location.lights.find(params[:id])

    respond_to do |format|
      if @light.update_attributes(params[:light])
        format.html { redirect_to([@location, @light], :notice => 'Light was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @light.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /lights/1
  # DELETE /lights/1.xml
  def destroy
    # @light = Light.find(params[:id])
    @location = Location.find(params[:location_id])
    @light = @location.lights.find(params[:id])
    @light.destroy

    respond_to do |format|
      format.html { redirect_to(location_lights_url) }
      format.xml  { head :ok }
    end
  end
  
  private
  
  def sort_column
    Light.column_names.include?(params[:sort]) ? params[:sort] : "name"
  end
  
  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end
  
end

app/helpers/lights_helper.rb
module LightsHelper
end

app/views/lights/_dragdropform.html.erb
<%= form_for([@location, @light]) do |f| %>
  <% if @light.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@light.errors.count, "error") %> prohibited this light from being saved:</h2>

      <ul>
      <% @light.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">

    <%= f.hidden_field :name %>
  </div>
  <div class="field">

    <%= f.hidden_field :location_id %>
  </div>
  <div class="field">

    <%= f.hidden_field :x_position %>
  </div>
  <div class="field">

    <%= f.hidden_field :y_position %>
  </div>
  <div class="field">

    <%= f.hidden_field :z_position %>
  </div>
  <div class="field">

    <%= f.hidden_field :light_id %>
  </div>
  <div class="field">

    <%= f.hidden_field :content %>
  </div>
  <div class="actions" onmouseover="updatelights()">
    <%= f.submit %>
  </div>
<% end %>

app/views/lights/_form.html.erb
<%= form_for([@location, @light]) do |f| %>
  <% if @light.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@light.errors.count, "error") %> prohibited this light from being saved:</h2>

      <ul>
      <% @light.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :x_position %><br />
    <%= f.text_field :x_position %>
  </div>
  <div class="field">
    <%= f.label :y_position %><br />
    <%= f.text_field :y_position %>
  </div>
  <div class="field">
    <%= f.label :z_position %><br />
    <%= f.text_field :z_position %>
  </div>
  <div class="field">
    <%= f.label :location_id %><br />
    <%= f.text_field :location_id,:readonly => true %>
  </div>
  <div class="field">
    <%= f.label :"Frequency" %><br />
    <%= f.text_field :light_id %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_field :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
  

<% end %>

app/views/lights/_newlightform.html.erb
<%= form_for([@location, @light]) do |f| %>
  <% if @light.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@light.errors.count, "error") %> prohibited this light from being saved:</h2>

      <ul>
      <% @light.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">

    <%= f.hidden_field :location_id %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">

    <%= f.hidden_field :x_position %>
  </div>
  <div class="field">

    <%= f.hidden_field :y_position %>
  </div>
  <div class="field">
    <%= f.label :"Z position (m)" %><br />
    <%= f.text_field :z_position %>
  </div>
  <div class="field">
    <%= f.label :"Light ID" %><br />
    <%= f.text_field :light_id %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_field :content %>
  </div>
  <div class="actions">
    
<%= f.submit %>
  </div>
<% end %>

app/views/lights/dragdrop.html.erb
<% content_for :head do %>

      <script language="JavaScript1.2" src="/main.js" type="text/javascript"></script> 
      <script type="text/javascript" src="/jquery.js"></script>
      <script type="text/javascript" src="/jquery-ui.min.js"></script>
      <script type="text/javascript" src="/prototype.js"></script>
      <link rel="stylesheet" type="text/css" href="/speechbubbles.css" />
      <script src="/speechbubbles.js">

/***********************************************
* Speech Bubbles Tooltip- (c) Dynamic Drive (www.dynamicdrive.com)
* This notice MUST stay intact for legal use
* Visit http://www.dynamicdrive.com/ for this script and 100s more.
***********************************************/

</script>

<script type="text/javascript">function updatelights(){ 
  var position = jQuery("#icon").position();
  document.getElementById("light_x_position").value = position.left;
  document.getElementById("light_y_position").value = position.top;
  document.getElementById("icon").title = "X position (m): "+PXtoM(position.left)+" </br> Y position (m): "+PXtoM(position.top)+"";
  jQuery('#icon').speechbubble();
  
}; </script>

<script type="text/javascript">function initialize(){ 
jQuery(function(jQuery){ //on document.ready
 	//Apply tooltip to links with class="addspeech", plus look inside 'speechdata.txt' for the tooltip markups
	jQuery('#icon').speechbubble();
})

  // Alert the position with jQuery
  var position = jQuery("#icon").position();
  document.getElementById("light_x_position").value = position.left;
  document.getElementById("light_y_position").value = position.top;
  document.getElementById("icon").title = "X position (m): "+PXtoM(position.left)+" </br> Y position (m): "+PXtoM(position.top)+"";
}; </script>

<script type="text/javascript">

jQuery( init );

function init() {
  jQuery('#icon').draggable();
}



</script>
<% end %>

  <div class="field">
    <b>Drag and drop light to desired position.</b><br />

  </div>


<div id = "home" style="position:relative; z-index:0;" onmouseover="updatelights()"><img src="<%= @location.photo.url(:original) %>" alt="Indoor Map"/>
<%= render 'newlightform' %>
<div id = "icon"   style="position:absolute; top: <%= @light.y_position %>px; left: <%= @light.x_position %>px; z-index:<%= @light.z_position %>" onmouseover="updatelights()"><img src="/images/light.png" alt="Senior Lab"/></div>

</div>

app/views/lights/edit.html.erb
<h1>Editing light</h1>

<%= render 'form' %>

<%= link_to 'Show', [@location, @light] %> |
<%= link_to 'Back', location_lights_path %>

app/views/lights/index.html.erb
<% content_for :head do %>
<script type="text/javascript">jQuery.noConflict();  </script>
<% end %>

<h1>Lights for <%= @location.name %></h1>


<table>
  <tr>
    <th>Name</th>
    <th>Light ID</th>
    <th>X (m)</th>
    <th>Y (m)</th>
    <th>Z (m)</th>
    <th>Content</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @lights.each do |light| %>
  <tr>
    <td><%= light.name %></td>
    <td><%= light.light_id %></td>
    <td><script type="text/javascript">document.write(PXtoM(<%= light.x_position %>));</script></td>
    <td><script type="text/javascript">document.write(PXtoM(<%= light.y_position %>));</script></td>
    <td><%= light.z_position %></td>
    
    <td><%= link_to light.content, light.content %></td>
    <td><%= link_to 'Details', [@location, light] %></td>
    <td><%= link_to 'Edit', dragdrop_location_light_path(@location, light) %><td>

    <td><%= link_to 'Delete', [@location, light], :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />
<%= link_to 'New Light', newlight_location_lights_path(@location) %>
<br>

<%= link_to 'Indoor Map', indoor_location_path(@location) %>

app/views/lights/new.html.erb
<% content_for :head do %>

    <title>Senior Lab</title>
      <script language="JavaScript1.2" src="/main.js" type="text/javascript"></script> 
      <script type="text/javascript" src="/jquery.js"></script>
      <script type="text/javascript" src="/jquery-ui.min.js"></script>
      <script type="text/javascript" src="/prototype.js"></script>
      <link rel="stylesheet" type="text/css" href="/speechbubbles.css" />
      <script src="/speechbubbles.js">

/***********************************************
* Speech Bubbles Tooltip- (c) Dynamic Drive (www.dynamicdrive.com)
* This notice MUST stay intact for legal use
* Visit http://www.dynamicdrive.com/ for this script and 100s more.
***********************************************/

</script>
<script type="text/javascript">function updatelights(){ 

  // Alert the position with jQuery
  var position = jQuery("#icon").position();
     document.getElementById("light_x_position").value = position.left;
     document.getElementById("light_y_position").value = position.top;
     document.getElementById("icon").title = "X position (m): "+PXtoM(position.left)+" </br> Y position (m): "+PXtoM(position.top)+"";
	jQuery('#icon').speechbubble('');
     
    
}; </script>

<script type="text/javascript">function initialize(){ 
        var  mapheight = jQuery("#map").height();
        var  mapwidth  = jQuery("#map").width();

         document.getElementById("icon").style.top = 100 +"px";
         document.getElementById("icon").style.left = 100 +"px";
         
         
  // Alert the position with jQuery
        var position = jQuery("#icon").position();
     document.getElementById("light_x_position").value = position.left;
     document.getElementById("light_y_position").value = position.top;
     document.getElementById("icon").title = "X position (m): "+PXtoM(position.left)+" </br> Y position (m): "+PXtoM(position.top)+"";
	jQuery('#icon').speechbubble('');
        
}; </script>


<script type="text/javascript">

jQuery(function(jQuery){ //on document.ready
 	//Apply tooltip to links with class="addspeech", plus look inside 'speechdata.txt' for the tooltip markups
	jQuery('#icon').speechbubble('');
})

</script>
      <script type="text/javascript">
      

jQuery( init );

function init() {
  jQuery('#icon').draggable();
}

jQuery.noConflict();

</script>
<% end %>


<div id = "map" style="position:relative; z-index:0;">
<img src="<%= @location.photo.url %>" onmouseover="updatelights()" alt="Indoor Map"/>
<div id = "icon"   style="position:absolute; z-index:4"><img src="/images/light.png" alt="Senior Lab"/></div>

</div>



<script language="JavaScript1.2" src="style.js" type="text/javascript"></script>  
 <script type="text/javascript"></script>

<div style="position:relative"> <%= render 'newlightform' %> </div>
</body>

app/views/lights/newlight.html.erb
<% content_for :head do %>

    <title>Senior Lab</title>
      <script language="JavaScript1.2" src="/main.js" type="text/javascript"></script> 
      <script type="text/javascript" src="/jquery.js"></script>
      <script type="text/javascript" src="/jquery-ui.min.js"></script>
      <script type="text/javascript" src="/prototype.js"></script>
      <link rel="stylesheet" type="text/css" href="/speechbubbles.css" />
      <script src="/speechbubbles.js">

/***********************************************
* Speech Bubbles Tooltip- (c) Dynamic Drive (www.dynamicdrive.com)
* This notice MUST stay intact for legal use
* Visit http://www.dynamicdrive.com/ for this script and 100s more.
***********************************************/

</script>
<script type="text/javascript">function updatelights(){ 

  // Alert the position with jQuery
  var position = jQuery("#icon").position();
     document.getElementById("light_x_position").value = position.left;
     document.getElementById("light_y_position").value = position.top;
     document.getElementById("icon").title = "X position (m): "+PXtoM(position.left)+" </br> Y position (m): "+PXtoM(position.top)+"";
	jQuery('#icon').speechbubble('');
     
    
}; </script>

<script type="text/javascript">function initialize(){ 
        var  mapheight = jQuery("#map").height();
        var  mapwidth  = jQuery("#map").width();

         document.getElementById("icon").style.top = 100 +"px";
         document.getElementById("icon").style.left = 100 +"px";
         
         
  // Alert the position with jQuery
        var position = jQuery("#icon").position();
     document.getElementById("light_x_position").value = position.left;
     document.getElementById("light_y_position").value = position.top;
     document.getElementById("icon").title = "X position (m): "+PXtoM(position.left)+" </br> Y position (m): "+PXtoM(position.top)+"";
	jQuery('#icon').speechbubble('');
        
}; </script>


<script type="text/javascript">

jQuery(function(jQuery){ //on document.ready
 	//Apply tooltip to links with class="addspeech", plus look inside 'speechdata.txt' for the tooltip markups
	jQuery('#icon').speechbubble('');
})

</script>
      <script type="text/javascript">
      

jQuery( init );

function init() {
  jQuery('#icon').draggable();
}

jQuery.noConflict();

</script>
<% end %>

  <div class="field">
    <b>Drag and drop light to desired position.</b><br />

  </div>
<div id = "map" style="position:relative; z-index:0;">
<img src="<%= @location.photo.url(:original) %>" onmouseover="updatelights()" alt="Indoor Map"/>
<div id = "icon"   style="position:absolute; z-index:4"><img src="/images/light.png" alt="Senior Lab"/></div>

</div>



<script language="JavaScript1.2" src="style.js" type="text/javascript"></script>  
 <script type="text/javascript"></script>

<div style="position:relative"> <%= render 'newlightform' %> </div>
</body>

app/views/lights/show.html.erb
<% content_for :head do %>
<script type="text/javascript">jQuery.noConflict();  </script>
<% end %>

<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @light.name %>
</p>

<p>
  <b>Location:</b>
  <%= @light.location_id %>
</p>

<p>
  <b>X position (m):</b>
  <script type="text/javascript">document.write(PXtoM(<%= @light.x_position %>));</script>
</p>

<p>
  <b>Y position (m):</b>
  <script type="text/javascript">document.write(PXtoM(<%= @light.y_position %>));</script>
</p>

<p>
  <b>Z position (m):</b>
  <%= @light.z_position %>
</p>

<p>
  <b>Light ID:</b>
  <%= @light.light_id %>
</p>

<p>
  <b>Content:</b>
  <%= @light.content %>
</p>

<%= link_to 'Edit', dragdrop_location_light_path(@location, @light) %>

<%= link_to 'Back', location_lights_path %>