config/routes.rb
ServerScaffold::Application.routes.draw do
  get "sessions/new"

  resources :histories do
    collection do
      get :destroy_all
    end
  end

  resources :devices
  
  resources :sessions, only: [:new, :create, :destroy]
  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  
  resources :locations do
    collection do
      get :newlocation
    end
    member do
      get :indoor
    end
    resources :lights do
      collection do
        get :newlight
      end
      member do
        get :dragdrop
      end
    end
  end

  resources :users

  root :to => "pages#home"

  match '/about',   :to => 'pages#about'

  match '/signup',  :to => 'users#new'
  
end

#== Route Map
# Generated on 30 Apr 2012 18:08
#
#    destroy_all_histories GET    /histories/destroy_all(.:format)                      {:action=>"destroy_all", :controller=>"histories"}
#                histories GET    /histories(.:format)                                  {:action=>"index", :controller=>"histories"}
#                          POST   /histories(.:format)                                  {:action=>"create", :controller=>"histories"}
#              new_history GET    /histories/new(.:format)                              {:action=>"new", :controller=>"histories"}
#             edit_history GET    /histories/:id/edit(.:format)                         {:action=>"edit", :controller=>"histories"}
#                  history GET    /histories/:id(.:format)                              {:action=>"show", :controller=>"histories"}
#                          PUT    /histories/:id(.:format)                              {:action=>"update", :controller=>"histories"}
#                          DELETE /histories/:id(.:format)                              {:action=>"destroy", :controller=>"histories"}
#                  devices GET    /devices(.:format)                                    {:action=>"index", :controller=>"devices"}
#                          POST   /devices(.:format)                                    {:action=>"create", :controller=>"devices"}
#               new_device GET    /devices/new(.:format)                                {:action=>"new", :controller=>"devices"}
#              edit_device GET    /devices/:id/edit(.:format)                           {:action=>"edit", :controller=>"devices"}
#                   device GET    /devices/:id(.:format)                                {:action=>"show", :controller=>"devices"}
#                          PUT    /devices/:id(.:format)                                {:action=>"update", :controller=>"devices"}
#                          DELETE /devices/:id(.:format)                                {:action=>"destroy", :controller=>"devices"}
#                 sessions POST   /sessions(.:format)                                   {:action=>"create", :controller=>"sessions"}
#              new_session GET    /sessions/new(.:format)                               {:action=>"new", :controller=>"sessions"}
#                  session DELETE /sessions/:id(.:format)                               {:action=>"destroy", :controller=>"sessions"}
#                   signup        /signup(.:format)                                     {:controller=>"users", :action=>"new"}
#                   signin        /signin(.:format)                                     {:controller=>"sessions", :action=>"new"}
#                  signout DELETE /signout(.:format)                                    {:controller=>"sessions", :action=>"destroy"}
#    newlocation_locations GET    /locations/newlocation(.:format)                      {:action=>"newlocation", :controller=>"locations"}
#          indoor_location GET    /locations/:id/indoor(.:format)                       {:action=>"indoor", :controller=>"locations"}
# newlight_location_lights GET    /locations/:location_id/lights/newlight(.:format)     {:action=>"newlight", :controller=>"lights"}
#  dragdrop_location_light GET    /locations/:location_id/lights/:id/dragdrop(.:format) {:action=>"dragdrop", :controller=>"lights"}
#          location_lights GET    /locations/:location_id/lights(.:format)              {:action=>"index", :controller=>"lights"}
#                          POST   /locations/:location_id/lights(.:format)              {:action=>"create", :controller=>"lights"}
#       new_location_light GET    /locations/:location_id/lights/new(.:format)          {:action=>"new", :controller=>"lights"}
#      edit_location_light GET    /locations/:location_id/lights/:id/edit(.:format)     {:action=>"edit", :controller=>"lights"}
#           location_light GET    /locations/:location_id/lights/:id(.:format)          {:action=>"show", :controller=>"lights"}
#                          PUT    /locations/:location_id/lights/:id(.:format)          {:action=>"update", :controller=>"lights"}
#                          DELETE /locations/:location_id/lights/:id(.:format)          {:action=>"destroy", :controller=>"lights"}
#                locations GET    /locations(.:format)                                  {:action=>"index", :controller=>"locations"}
#                          POST   /locations(.:format)                                  {:action=>"create", :controller=>"locations"}
#             new_location GET    /locations/new(.:format)                              {:action=>"new", :controller=>"locations"}
#            edit_location GET    /locations/:id/edit(.:format)                         {:action=>"edit", :controller=>"locations"}
#                 location GET    /locations/:id(.:format)                              {:action=>"show", :controller=>"locations"}
#                          PUT    /locations/:id(.:format)                              {:action=>"update", :controller=>"locations"}
#                          DELETE /locations/:id(.:format)                              {:action=>"destroy", :controller=>"locations"}
#                    users GET    /users(.:format)                                      {:action=>"index", :controller=>"users"}
#                          POST   /users(.:format)                                      {:action=>"create", :controller=>"users"}
#                 new_user GET    /users/new(.:format)                                  {:action=>"new", :controller=>"users"}
#                edit_user GET    /users/:id/edit(.:format)                             {:action=>"edit", :controller=>"users"}
#                     user GET    /users/:id(.:format)                                  {:action=>"show", :controller=>"users"}
#                          PUT    /users/:id(.:format)                                  {:action=>"update", :controller=>"users"}
#                          DELETE /users/:id(.:format)                                  {:action=>"destroy", :controller=>"users"}
#                     root        /(.:format)                                           {:controller=>"pages", :action=>"home"}
#                    about        /about(.:format)                                      {:controller=>"pages", :action=>"about"}
#                                 /signup(.:format)                                     {:controller=>"users", :action=>"new"}

app/models/location.rb
# == Schema Information
#
# Table name: locations
#
#  id                 :integer         not null, primary key
#  location_id        :integer
#  latitude           :decimal(, )
#  longitude          :decimal(, )
#  map                :string(255)
#  name               :string(255)
#  email              :string(255)
#  created_at         :datetime
#  updated_at         :datetime
#  photo_file_name    :string(255)
#  photo_content_type :string(255)
#  photo_file_size    :integer
#  photo_updated_at   :datetime
#  photo_url          :string(255)
#

class Location < ActiveRecord::Base

  attr_accessible :latitude, :longitude, :map, :name, :photo, :photo_file_name, :photo_content_type, :photo_file_size, :photo_updated_at, :photo_url

  has_many :lights
  has_many :devices
  has_many :histories

  belongs_to :user

  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :latitude, :presence => true

  validates :longitude, :presence => true

  #validates :map, :presence => true

  validates :name, :presence => true,
                   :length   => { :maximum => 30 }

#  validates :email, :presence => true,
#                    :format   => { :with => email_regex },
#                    :uniqueness => { :case_sensitive => false }

  has_attached_file :photo,
  :storage => :s3,
  :s3_credentials => "#{RAILS_ROOT}/config/s3.yml",
  :path => ":attachment/:id/:style.:extension",
  :bucket => 'bu-ece',
  :url => ':s3_domain_url',
  :s3_permissions => 'public-read',
  :s3_protocol => 'http',
  :styles => {
    :thumb  => "100x100",
    :medium => "200x200",
    :large => "600x400"
  },
  :default_url => "/images/nomap.bmp"
    
  validates_attachment_content_type :photo, :content_type => [ 'image/jpeg', 'image/png', 'image/gif', 'image/jpg', 'image/bmp'  ], :message => "is not an acceptable image file" 



  def self.search(search)

    if search 
      find(:all, :conditions => ['name ILIKE?', "%#{search.downcase}%"])
    else
      find(:all)
    end
  end
  
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController

  helper_method :sort_column, :sort_direction
  
  # GET /locations
  # GET /locations.xml
  def index
    @locations = Location.search(params[:search])
    #@locations = Location.order(sort_column + " " + sort_direction)
    @title = "Locations"

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @locations }
      format.json  { render :json => @locations }
    end
  end
  
  # GET /locations/1/indoor
  # GET /locations/1/indoor.xml
  def indoor
    @location = Location.find(params[:id])
    @lights = @location.lights.all
    
    respond_to do |format|
      format.html # indoor.html.erb
      format.xml  { render :xml => @lights }
      format.json  { render :json => @lights }
    end  
  end

  # GET /locations/1
  # GET /locations/1.xml
  def show
    @location = Location.find(params[:id])
    @lights = @location.lights.all

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @location }
      format.json  { render :json => @location }
    end
  end
  
  # GET /locations/newlocation
  # GET /locations/newlocation.xml
  def newlocation
    @location = Location.new

    respond_to do |format|
      format.html # newlocation.html.erb
      format.xml  { render :xml => @location }
    end
  end
  
  # GET /locations/new
  # GET /locations/new.xml
  def new
    @location = Location.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @location }
    end
  end

  # GET /locations/1/edit
  def edit
    @location = Location.find(params[:id])
  end

  # POST /locations
  # POST /locations.xml
  def create
    @location = Location.new(params[:location])
    
    respond_to do |format|
      if @location.save
        @location.update_attribute(:photo_url, @location.photo.url)
        format.html { redirect_to(@location, :notice => 'Location was successfully created.') }
        format.xml  { render :xml => @location, :status => :created, :location => @location }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @location.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /locations/1
  # PUT /locations/1.xml
  def update
    @location = Location.find(params[:id])
    respond_to do |format|
      if @location.update_attributes(params[:location])
        @location.update_attribute(:photo_url, @location.photo.url)
        format.html { redirect_to(@location, :notice => 'Location was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @location.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.xml
  def destroy
    @location = Location.find(params[:id])
    @location.destroy

    respond_to do |format|
      format.html { redirect_to(locations_url) }
      format.xml  { head :ok }
    end
  end
  
  private
  
  def sort_column
    Location.column_names.include?(params[:sort]) ? params[:sort] : "name"
  end
  
  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end  
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/locations/_form.html.erb
<%= form_for @location, :html => {:multipart => true} do |f| %>
  <% if @location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
      <% @location.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<!--  <div class="field">
    <%= f.label :location_id %><br />
    <%= f.text_field :location_id %>
  </div>-->
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
  <%= f.label :"Map" %><br/ >
  <%= f.file_field :photo %>
  </div>
  <div>
  Latitude and longitude cannot be changed.  Create a new location instead.
  <br/>
  </div>
  <br/>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/locations/_newlocationform.html.erb
<%= form_for @location, :html => {:multipart => true} do |f| %>
  <% if @location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
      <% @location.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
  <%= f.label :"Upload map" %><br/ >
  Acceptable image type: JPG, JPEG, GIF, BMP, PNG<br>
  <%= f.file_field :photo %>
  </div>
  <div class="field">
    <%= f.label :"Coordinates" %>   <br>Right click on map to get coordinates.<br />
    Lat: <%= f.text_field :latitude,:readonly => true %> Long: <%= f.text_field :longitude,:readonly => true %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/locations/edit.html.erb
<h1>Editing location</h1>

<%= render 'form' %>

<%= link_to 'Show', @location %> |
<%= link_to 'Back', locations_path %>

app/views/locations/index.html.erb
<% content_for :head do %>
    <meta name="viewport" content="initial-scale=1.0, user-scalable=no" />
    <style type="text/css">
      html { height: 100% }
      body { height: 100%; margin: 0; padding: 0 }
      #map_canvas { height: 100% }
    </style>
    
    <script type="text/javascript"
      src="http://maps.googleapis.com/maps/api/js?key=AIzaSyDNsmG-CODbm8HLec1SOZBwGCb9HpRmExU&sensor=false">
    </script>
    
  
    <script type="text/javascript">
       var arrMarkers = [];
       var arrInfoWindows = [];

      function initialize() {
        var myOptions = {
          center: new google.maps.LatLng(42.350112,-71.106171),
          zoom: 17,
          mapTypeId: google.maps.MapTypeId.ROADMAP };
        var map = new google.maps.Map(document.getElementById("map_canvas"),myOptions);
      
      

      jQuery.getJSON("locations.json", {}, function(json){

 jQuery.each(json, function(i,item){jQuery("#markers").append('<li><a href="#" rel="' + i + '">' + item.location.name + '</a></li>');



              var marker = new google.maps.Marker({position: new google.maps.LatLng(item.location.latitude,item.location.longitude),map: map,title: item.location.name});

                arrMarkers[i] = marker;

});
});


}


    </script>
<% end %>

<h1>Locations</h1>

<% form_tag locations_path, :method => 'get' do %>
<p>
  <%= text_field_tag :search, params[:search] %>
  <%= submit_tag "Search" , :name => nil%>
</p>
<% end %>

<table>
  <tr>
    <th>Name</th>
    <th>Latitude</th>
    <th>Longitude</th>
    <th>Map</th>
    <th></th>
    <th></th>
    <!--<th></th>-->
  </tr>

<% @locations.each do |location| %>
  <tr>
    <td><%= location.name %></td>
    <td><script type="text/javascript">document.write(<%= location.latitude%>.toFixed(5));</script></td>
    <td><script type="text/javascript">document.write(<%= location.longitude%>.toFixed(5));</script></td>
    <td><img src="<%= location.photo.url(:thumb) %>" height=100px></td>
    <td><%= link_to 'Details', location %></td>
    <td><%= link_to 'Lights', location_lights_path(location) %></td>
    <!--<td><%= link_to 'Delete', location, :confirm => 'Are you sure?', :method => :delete %></td>-->
  </tr>
<% end %>
</table>

<br>
<%= link_to 'New Location', newlocation_locations_path %>

<% content_for :map do %>

<section class="round">

<div id="map_canvas" style="width:670px; height:400px"></div>

</section>

<% end %>

app/views/locations/indoor.html.erb
<% content_for :head do %>
 
  <script src="/javascripts/prototype.js?1331930482" type="text/javascript"></script>
<script src="/javascripts/effects.js?1331930482" type="text/javascript"></script>
<script src="/javascripts/dragdrop.js?1331930482" type="text/javascript"></script>
<script src="/javascripts/controls.js?1331930482" type="text/javascript"></script>
<script src="/javascripts/rails.js?1331930482" type="text/javascript"></script>
<script src="/javascripts/application.js?1331930482" type="text/javascript"></script>
<script src="/javascripts/jquery.js?1332185405" type="text/javascript"></script>
<script src="/javascripts/jquery.rails.js?1332192435" type="text/javascript"></script>
      <script language="JavaScript1.2" src="/main.js" type="text/javascript"></script> 
      <script type="text/javascript" src="/jquery.js"></script>
      <script type="text/javascript" src="/jquery-ui.min.js"></script>
      <script type="text/javascript" src="/prototype.js"></script>
      <link rel="stylesheet" type="text/css" href="/speechbubbles.css" />
      <script src="/speechbubbles.js">

/***********************************************
* Speech Bubbles Tooltip- (c) Dynamic Drive (www.dynamicdrive.com)
* This notice MUST stay intact for legal use
* Visit http://www.dynamicdrive.com/ for this script and 100s more.
***********************************************/

</script>

<script type="text/javascript">
      


</script>
<% end %>




<div id = "home" style="position:relative; z-index:0;"><img src="<%= @location.photo.url(:original) %>" alt="Indoor Map"/>
</div>


<script type="text/javascript">




jQuery.getJSON("/locations/<%= @location.id %>/lights.json", {}, function(json){

  jQuery.each(json, function(i, item){
  
    jQuery('#home').append('<div id="icon'+i+'" title="Name: '+item.light.name+' </br> X position (m): '+PXtoM(item.light.x_position)+' </br> Y position (m): '+PXtoM(item.light.y_position)+' </br> Z position (m): '+item.light.z_position+' </br> Light ID: '+item.light.light_id+' </br> Content: '+item.light.content+'  " style="position:absolute; top: '+ item.light.y_position +'px; left: '+ item.light.x_position +'px; z-index: '+ item.light.z_position +'"><img src="/images/light.png"></ div>' );

    jQuery(function(jQuery){ //on document.ready
    
 	  //Apply tooltip to links with class="addspeech", plus look inside 'speechdata.txt' for the tooltip markups
 	    
	  jQuery('#icon'+i+'').speechbubble();
	  
    })
    

    
  });
});

</script>

app/views/locations/new.html.erb
<% content_for :head do %>
    <meta name="viewport" content="initial-scale=1.0, user-scalable=no" />
    <style type="text/css">
      html { height: 100% }
      body { height: 100%; margin: 0; padding: 0 }
      #map_canvas { height: 100% }

#contextMenu {
	position: absolute;
	min-width: 100px;
	z-index: 1000;
	background: #fff;
	border-top: solid 1px #CCC;
	border-left: solid 1px #CCC;
	border-bottom: solid 1px #676767;
	border-right: solid 1px #676767;
	padding: 0px;
	margin: 0px;
	display:none;
}

#contextMenu a {
	color: #000;
	text-decoration: none;
	display: block;
	line-height: 22px;
	height: 22px;
	padding: 1px 10px;
}

#contextMenu li {
	list-style: none;
	padding: 1px;
	margin: 0px;
}

#contextMenu li.hover a {
	background-color: #A7C4FA;
}

#contextMenu li.separator {
	border-top: solid 1px #ccc;
}

    </style>
    <script type="text/javascript"
      src="http://maps.googleapis.com/maps/api/js?key=AIzaSyDNsmG-CODbm8HLec1SOZBwGCb9HpRmExU&sensor=false">
    </script>
    

    
    <script type="text/javascript">
       var arrMarkers = [];
       var arrInfoWindows = [];
      function initialize() {
        var myOptions = {
          center: new google.maps.LatLng(42.350112,-71.106171),
          zoom: 17,
          mapTypeId: google.maps.MapTypeId.ROADMAP };
        var map = new google.maps.Map(document.getElementById("map_canvas"),myOptions);

        
      
      jQuery.noConflict();

    var contextMenu = jQuery(document.createElement('ul'))
	.attr('id', 'contextMenu');      

   contextMenu.append(
	'<li><a href="#createlocation">Create a New Location</a></li>' 
);
  
jQuery(map.getDiv()).append(contextMenu);

// Keep track of where you clicked
var clickedLatLng;
var locationlong;
var locationlat; 

// Display and position the menu
google.maps.event.addListener(map, 'rightclick', function(e)
{
	// start buy hiding the context menu if its open
	contextMenu.hide();
        locationlong = e.latLng.lng();
        locationlat = e.latLng.lat(); 
	var mapDiv = jQuery(map.getDiv()),
		x = e.pixel.x,
		y = e.pixel.y;

	// save the clicked location
	clickedLatLng = e.latLng;

	// adjust if clicked to close to the edge of the map
	if ( x > mapDiv.width() - contextMenu.width() )
		x -= contextMenu.width();

	if ( y > mapDiv.height() - contextMenu.height() )
		y -= contextMenu.height();

	// Set the location and fade in the context menu
	contextMenu.css({ top: y, left: x }).fadeIn(100);
});

// Set some events on the context menu links
contextMenu.find('a').click( function()
{
	// fade out the menu
	contextMenu.fadeOut(75);

	// The link's href minus the #
	var action = jQuery(this).attr('href').substr(1);

	switch ( action )
	{
		case 'createlocation':
                        map.panTo(clickedLatLng);
			
                        
                        document.getElementById("location_latitude").value = locationlat;
                        document.getElementById("location_longitude").value = locationlong;
			
			
			break;
	}

	return false;
});

// Hover events for effect
contextMenu.find('a').hover( function() {
	jQuery(this).parent().addClass('hover');
}, function() {
	jQuery(this).parent().removeClass('hover');
});

// Hide context menu on some events
jQuery.each('click dragstart zoom_changed maptypeid_changed'.split(' '), function(i,name){
	google.maps.event.addListener(map, name, function(){ contextMenu.hide() });
});

    jQuery.getJSON("/locations.json", {}, function(json){

 jQuery.each(json, function(i,item){jQuery("#markers").append('<li><a href="#" rel="' + i + '">' + item.location.name + '</a></li>');



              var marker = new google.maps.Marker({position: new google.maps.LatLng(item.location.latitude,item.location.longitude),map: map,title: item.location.name});

                arrMarkers[i] = marker;

});
});


}

    </script>

<% end %>
  
  <%= render 'newlocationform' %>

<%= link_to 'Back', locations_path %>


<br/>
  
<div id="map_canvas" style="width:670px; height:400px"></div>

app/views/locations/newlocation.html.erb
<% content_for :head do %>
    <meta name="viewport" content="initial-scale=1.0, user-scalable=no" />
    <style type="text/css">
      html { height: 100% }
      body { height: 100%; margin: 0; padding: 0 }
      #map_canvas { height: 100% }

#contextMenu {
	position: absolute;
	min-width: 100px;
	z-index: 1000;
	background: #fff;
	border-top: solid 1px #CCC;
	border-left: solid 1px #CCC;
	border-bottom: solid 1px #676767;
	border-right: solid 1px #676767;
	padding: 0px;
	margin: 0px;
	display:none;
}

#contextMenu a {
	color: #000;
	text-decoration: none;
	display: block;
	line-height: 22px;
	height: 22px;
	padding: 1px 10px;
}

#contextMenu li {
	list-style: none;
	padding: 1px;
	margin: 0px;
}

#contextMenu li.hover a {
	background-color: #A7C4FA;
}

#contextMenu li.separator {
	border-top: solid 1px #ccc;
}

    </style>
    <script type="text/javascript"
      src="http://maps.googleapis.com/maps/api/js?key=AIzaSyDNsmG-CODbm8HLec1SOZBwGCb9HpRmExU&sensor=false">
    </script>
    

    
    <script type="text/javascript">
       var arrMarkers = [];
       var arrInfoWindows = [];
      function initialize() {
        var myOptions = {
          center: new google.maps.LatLng(42.350112,-71.106171),
          zoom: 17,
          mapTypeId: google.maps.MapTypeId.ROADMAP };
        var map = new google.maps.Map(document.getElementById("map_canvas"),myOptions);

        
      
      jQuery.noConflict();

    var contextMenu = jQuery(document.createElement('ul'))
	.attr('id', 'contextMenu');      

   contextMenu.append(
	'<li><a href="#createlocation">Create a New Location</a></li>' 
);
  
jQuery(map.getDiv()).append(contextMenu);

// Keep track of where you clicked
var clickedLatLng;
var locationlong;
var locationlat; 

// Display and position the menu
google.maps.event.addListener(map, 'rightclick', function(e)
{
	// start buy hiding the context menu if its open
	contextMenu.hide();
        locationlong = e.latLng.lng();
        locationlat = e.latLng.lat(); 
	var mapDiv = jQuery(map.getDiv()),
		x = e.pixel.x,
		y = e.pixel.y;

	// save the clicked location
	clickedLatLng = e.latLng;

	// adjust if clicked to close to the edge of the map
	if ( x > mapDiv.width() - contextMenu.width() )
		x -= contextMenu.width();

	if ( y > mapDiv.height() - contextMenu.height() )
		y -= contextMenu.height();

	// Set the location and fade in the context menu
	contextMenu.css({ top: y, left: x }).fadeIn(100);
});

// Set some events on the context menu links
contextMenu.find('a').click( function()
{
	// fade out the menu
	contextMenu.fadeOut(75);

	// The link's href minus the #
	var action = jQuery(this).attr('href').substr(1);

	switch ( action )
	{
		case 'createlocation':
                        map.panTo(clickedLatLng);
			
                        
                        document.getElementById("location_latitude").value = locationlat;
                        document.getElementById("location_longitude").value = locationlong;
			
			
			break;
	}

	return false;
});

// Hover events for effect
contextMenu.find('a').hover( function() {
	jQuery(this).parent().addClass('hover');
}, function() {
	jQuery(this).parent().removeClass('hover');
});

// Hide context menu on some events
jQuery.each('click dragstart zoom_changed maptypeid_changed'.split(' '), function(i,name){
	google.maps.event.addListener(map, name, function(){ contextMenu.hide() });
});

    jQuery.getJSON("/locations.json", {}, function(json){

 jQuery.each(json, function(i,item){jQuery("#markers").append('<li><a href="#" rel="' + i + '">' + item.location.name + '</a></li>');



              var marker = new google.maps.Marker({position: new google.maps.LatLng(item.location.latitude,item.location.longitude),map: map,title: item.location.name});

                arrMarkers[i] = marker;

});
});


}

    </script>

<% end %>
  
  <%= render 'newlocationform' %>

<%= link_to 'Back', locations_path %>


<br/>
  
<div id="map_canvas" style="width:670px; height:400px"></div>

app/views/locations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @location.name %>
</p>

<p>
  <b>Latitude:</b>
  <%= @location.latitude %>
</p>

<p>
  <b>Longitude:</b>
  <%= @location.longitude %>
</p>

<p>
  <b>Map:</b>
  <%= image_tag @location.photo.url(:medium) %>
</p>

<%= link_to 'Edit', edit_location_path(@location) %> |
<%= link_to 'Back', locations_path %>